### ISSUE TITLE
Support for url based BrowserWindowOpener

### ISSUE THREAD

**Issue by kumlien** [bdunn44/vaadin-oauthpopup#2]
Hi,
I'm running a project using vaadin-spring-boot-starter. I then run into trouble when trying to use this add-on. Basically the popup window gets the wrong url to the Vaadin bootstrap.js. After some debugging in the SpringVaadinServlet, SpringVaadinServletRequest, BootstrapHandler and searching google + Vaadin forums I found the simplest solution to be to allow this add-on to accept popups based on URL:s in addition to popups based on UI:s. Then I can open a popup using a url pointing to a UI annotated with @SpringUI which makes vaadin-spring-boot happy...

**Comment by bdunn44** [comment]
Not sure I follow the problem or the solution, I've never used Spring. Do you have any code you can share?

If you are recommending an enhancement to the addon pull requests are always welcome.

**Comment by kumlien** [comment]
Hi, 
Not sure I understand 100% either :) But my understanding so far is that when running inside a Spring (Boot) MVC context with Vaadin then everything plays better together if the ui:s are registered as Spring Beans (using the @SpringUI annotation). I'm sure this cat can be skinned in some other way but this approach was the simplest one for me... Thanks for a great add-on btw, saved me quite a few lines of code!

**Comment by bdunn44** [comment]
Thanks for the PR! I'll review, integrate and release

**Comment by kumlien** [comment]
Hi there, any thoughts on this one?
br Svante

**Comment by bdunn44** [comment]
Resolved with release 1.0.0!

**Comment by kumlien** [comment]
Awesome!
